var s={},u,c,U,r,i,l=0,a,e=eval,w=String.fromCharCode,sucuri_cloudproxy_js='',S='eD0nMG1TNCcuc3Vic3RyKDMsIDEpICsgJycgKycnKyJlIi5zbGljZSgwLDEpICsgImJzdWN1ciIuY2hhckF0KDApKyIwbCIuY2hhckF0KDApICsgICcnICsgCiI4c3VjdXIiLmNoYXJBdCgwKSsnMCcgKyAgICcnICsnMmYnLnNsaWNlKDEsMikrJzUnICsgICIxIiArICIiICsiOXN1Ii5zbGljZSgwLDEpICsgImNzdWN1ciIuY2hhckF0KDApKyIiICsndUdmJy5jaGFyQXQoMikrJz0zJy5zbGljZSgxLDIpK1N0cmluZy5mcm9tQ2hhckNvZGUoMHgzMykgKyAnMicgKyAgJzInICsgICAnJyArJ2InICsgICI2ayIuY2hhckF0KDApICsgICcnICsgCiI3dyIuY2hhckF0KDApICsgImUiICsgIjMiICsgIiIgKyc5JyArICBTdHJpbmcuZnJvbUNoYXJDb2RlKDB4NjQpICsgIjciLnNsaWNlKDAsMSkgKyAgJycgKyAKIjlzdWN1ciIuY2hhckF0KDApKyAnJyArJzMnICsgICI1bSIuY2hhckF0KDApICsgICcnICsgCiI1c3UiLnNsaWNlKDAsMSkgKyAiIiArU3RyaW5nLmZyb21DaGFyQ29kZSgweDM5KSArICdWeD42Jy5zdWJzdHIoMywgMSkgKyAnJyArIjRzdWN1ciIuY2hhckF0KDApKyI5IiArICAnJyArJyc7ZG9jdW1lbnQuY29va2llPSdzc3VjdXJpJy5jaGFyQXQoMCkgKyAndXMnLmNoYXJBdCgwKSsnYycrJ3VzdScuY2hhckF0KDApICsnc3VjdXJyJy5jaGFyQXQoNSkgKyAnaScrJ19zdScuY2hhckF0KDApICsnc3VjdXJpYycuY2hhckF0KDYpKydsJy5jaGFyQXQoMCkrJ29zdWN1Jy5jaGFyQXQoMCkgICsnc3UnLmNoYXJBdCgxKSsnc3VjdXJkJy5jaGFyQXQoNSkgKyAncCcuY2hhckF0KDApKydyJysnJysnc3VjdXJpbycuY2hhckF0KDYpKyd4c3VjdScuY2hhckF0KDApICArJ3lzJy5jaGFyQXQoMCkrJ18nKyd1JysndScrJ2knKydkJysnX3N1Y3VyJy5jaGFyQXQoMCkrICc3Jysnc3VjdXJiJy5jaGFyQXQoNSkgKyAnNicrJzFzJy5jaGFyQXQoMCkrJ2NzdWN1cmknLmNoYXJBdCgwKSArICdiJy5jaGFyQXQoMCkrJzRzdScuY2hhckF0KDApICsnNXN1YycuY2hhckF0KDApKyAnZHMnLmNoYXJBdCgwKSsiPSIgKyB4ICsgJztwYXRoPS87bWF4LWFnZT04NjQwMCc7IGxvY2F0aW9uLnJlbG9hZCgpOw==';
L=S.length;
U=0;
r='';
var A='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
for(u=0;u<64;u++){
	s[A.charAt(u)]=u;
}
for(i=0;i<L;i++){
	c=s[S.charAt(i)];
	U=(U<<6)+c;
	l+=6;
	while(l>=8){
		((a=(U>>>(l-=8))&0xff)||(i<(L-2)))&&(r+=w(a));
	}
}
console.log(r)
//e(r);